Description: >

    This template deploys a VPC, with a pair of public and private subnets spread 
    across two Availabilty Zones. It deploys an Internet Gateway, with a default 
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ), 
    and default routes for them in the private subnets.
Parameters:

    DomainName:
        Description: Fully qualified domain name (FQDN) of the site that you want to secure with the ACM certificate
        Type: String
    KeyName:
        Description: Fully qualified domain name (FQDN) of the site that you want to secure with the ACM certificate
        Type: String

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/vpc.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
                DomainName: !Ref DomainName

    JenkinsCI:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/jenkins.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                # Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                VPC: !GetAtt VPC.Outputs.VPC
                Listener: !GetAtt ALB.Outputs.Listener
                JenkinsSecurityGroup: !GetAtt SecurityGroups.Outputs.JenkinsSecurityGroup
                KeyName: !Ref KeyName
