Description: >

    This template deploys a VPC, with a pair of public and private subnets spread 
    across two Availabilty Zones. It deploys an Internet Gateway, with a default 
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ), 
    and default routes for them in the private subnets.
Parameters:

    DomainName:
        Description: Fully qualified domain name (FQDN) of the site that you want to secure with the ACM certificate
        Type: String

    KeyName:
        Description: KeyName you would like for ssh access
        Type: String

    Certificate:
        Description: SSL certificate ARN
        Type: String

    S3Location:
        Description: S3 location for files
        Type: String

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/vpc.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    JenkinsELB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.JenkinsELBSG
                Certificate: !Ref Certificate
                DomainName: !Ref DomainName
                SubDomainName: jenkins

    JenkinsCI:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/acrdevelopment/danny/web-app/jenkins.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                VPC: !GetAtt VPC.Outputs.VPC
                LoadBalancerNames: !GetAtt JenkinsELB.Outputs.LoadBalancer
                JenkinsSecurityGroup: !GetAtt SecurityGroups.Outputs.JenkinsSecurityGroup
                KeyName: !Ref KeyName
                S3Location: !Ref S3Location
