Description: >
    This template contains the security groups required by our entire stack.
    We create them in a seperate nested template, so they can be referenced
    by all of the other nested templates.

Parameters:
    
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    
    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the security groups should be deployed to

Resources:

    JenkinsELBSG:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        VpcId: !Ref VPC
        GroupDescription: Access to the public load balancer
        SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            IpProtocol: tcp
            FromPort: '443'
            ToPort: '443'
        Tags: 
          - Key: Name
            Value: !Sub ${EnvironmentName}-Jenkins-ELB

    JenkinsSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: Jenkins
        SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref JenkinsELBSG
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 162.246.216.28/32
          IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
        VpcId: !Ref VPC
        Tags: 
          - Key: Name
            Value: !Sub ${EnvironmentName}-Jenkins

    EFSIngressRule:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        FromPort: 2049
        GroupId: !Sub ${JenkinsSecurityGroup}
        IpProtocol: tcp
        SourceSecurityGroupId: !Sub ${JenkinsSecurityGroup}
        ToPort: 2049

Outputs:

    JenkinsELBSG:
      Description: A reference to the security group for load balancers
      Value: !Ref JenkinsELBSG

    JenkinsSecurityGroup:
      Description: A reference to the security group for jenkins
      Value: !Ref JenkinsSecurityGroup
