version: 0.0
# version: Currently the only allowed value is 0.0. It is reserved by AWS CodeDeploy
# http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref-structure.html
os: linux
# Specify "os: linux" if this revision targets Amazon Linux, 
#   Red Hat Enterprise Linux (RHEL), or Ubuntu Server  
# Specify "os: windows" if this revision targets Windows Server instances.
# (You cannot specify both "os: linux" and "os: windows".)
files:
  # - source: main.go
  #   destination: /home/ubuntu/gocode/src/app
  # - source: /routers
  #   destination: /home/ubuntu/gocode/src/app/routers
  # - source: /tests
  #   destination: /home/ubuntu/gocode/src/app/tests
  # - source: /models
  #   destination: /home/ubuntu/gocode/src/app/models
  # - source: /controllers
  #   destination: /home/ubuntu/gocode/src/app/controllers

  - source: app
    destination: /home/ubuntu/gocode/src/app

  - source: /conf
    destination: /home/ubuntu/gocode/src/app/conf
  - source: /static
    destination: /home/ubuntu/gocode/src/app/static
  # - source: /vendor
  #   destination: /home/ubuntu/gocode/src/app/vendor
  - source: /views
    destination: /home/ubuntu/gocode/src/app/views
  - source: /start.sh
      destination: /home/ubuntu/gocode/src/app/start.sh
  - source: /stop.sh
      destination: /home/ubuntu/gocode/src/app/stop.sh
hooks:
